server:
  port: 8010
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        # sentinel API端口，默认UrlCleaner8719，由于8719被占用sentinel dashboard，故而设为8720
        # 如果不设置，也可启动，应用检测到8719被占用后，会自动+1，直到找到未被占用的端口
        port: 8720
management:
  endpoints:
    web:
      exposure:
        include: '*'
