spring:
  application:
    name: auth-server

server:
  servlet:
    context-path: /uaa
  port: 7777
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
